mods.jei.JEI.removeAndHide(<dse:hammeriron>);
mods.jei.JEI.removeAndHide(<dse:hammersteel>);
mods.jei.JEI.removeAndHide(<dse:components:1>);
mods.jei.JEI.removeAndHide(<dse:components:2>);
mods.jei.JEI.removeAndHide(<dse:components:6>);
mods.jei.JEI.removeAndHide(<dse:components:7>);
mods.jei.JEI.removeAndHide(<dse:components:10>);
mods.jei.JEI.removeAndHide(<dse:components:11>);
mods.jei.JEI.removeAndHide(<dse:components:12>);
